"""
markets_universe.py — the canonical list of tradable assets per exchange.

Previously this lived hard-coded inside the frontend JS. Centralizing it on
the backend makes it the single source of truth that drives the clickable
Markets dashboard and (optionally) bot creation.
"""

ALPACA_STOCKS = [
    ("AAPL", "Apple Inc."), ("MSFT", "Microsoft Corp."), ("GOOGL", "Alphabet Inc."),
    ("AMZN", "Amazon.com Inc."), ("NVDA", "NVIDIA Corp."), ("META", "Meta Platforms"),
    ("TSLA", "Tesla Inc."), ("BRK.B", "Berkshire Hathaway"), ("JPM", "JPMorgan Chase"),
    ("V", "Visa Inc."), ("UNH", "UnitedHealth Group"), ("XOM", "Exxon Mobil"),
    ("JNJ", "Johnson & Johnson"), ("PG", "Procter & Gamble"), ("MA", "Mastercard"),
    ("HD", "Home Depot"), ("AVGO", "Broadcom Inc."), ("LLY", "Eli Lilly"),
    ("ABBV", "AbbVie Inc."), ("MRK", "Merck & Co."), ("PEP", "PepsiCo"),
    ("KO", "Coca-Cola"), ("BAC", "Bank of America"), ("COST", "Costco Wholesale"),
    ("TMO", "Thermo Fisher"), ("NFLX", "Netflix Inc."), ("CRM", "Salesforce"),
    ("AMD", "Advanced Micro Devices"), ("ORCL", "Oracle Corp."), ("ACN", "Accenture"),
    ("DIS", "Walt Disney"), ("MCD", "McDonald's"), ("WMT", "Walmart Inc."),
    ("ADBE", "Adobe Inc."), ("TXN", "Texas Instruments"), ("INTC", "Intel Corp."),
    ("QCOM", "Qualcomm"), ("PFE", "Pfizer Inc."), ("INTU", "Intuit Inc."),
    ("IBM", "IBM Corp."), ("GS", "Goldman Sachs"), ("MS", "Morgan Stanley"),
    ("CSCO", "Cisco Systems"), ("NKE", "Nike Inc."), ("VZ", "Verizon"),
    ("T", "AT&T Inc."), ("CVX", "Chevron Corp."), ("UPS", "United Parcel Service"),
    ("RTX", "RTX Corp."), ("HON", "Honeywell"), ("CAT", "Caterpillar"),
    ("BA", "Boeing Co."), ("SPGI", "S&P Global"), ("NOW", "ServiceNow"),
    ("ISRG", "Intuitive Surgical"), ("DE", "Deere & Co."), ("GE", "GE Aerospace"),
    ("UNP", "Union Pacific"), ("PYPL", "PayPal Holdings"), ("SBUX", "Starbucks"),
    ("AXP", "American Express"), ("BKNG", "Booking Holdings"), ("ADP", "ADP Inc."),
    ("NEE", "NextEra Energy"), ("TMUS", "T-Mobile US"), ("ABT", "Abbott Labs"),
    ("BMY", "Bristol-Myers Squibb"), ("LIN", "Linde plc"), ("PM", "Philip Morris"),
    ("AMAT", "Applied Materials"), ("MU", "Micron Technology"), ("LRCX", "Lam Research"),
    ("REGN", "Regeneron"), ("GILD", "Gilead Sciences"), ("MDT", "Medtronic"),
    ("SYK", "Stryker Corp."), ("BLK", "BlackRock"), ("SCHW", "Charles Schwab"),
    ("TGT", "Target Corp."), ("WFC", "Wells Fargo"), ("C", "Citigroup"),
    ("USB", "U.S. Bancorp"), ("PNC", "PNC Financial"), ("TFC", "Truist Financial"),
    ("COF", "Capital One"), ("LOW", "Lowe's"), ("TJX", "TJX Companies"),
    ("CMCSA", "Comcast"), ("CHTR", "Charter Communications"), ("DHR", "Danaher"),
    ("ELV", "Elevance Health"), ("CI", "The Cigna Group"), ("HUM", "Humana"),
    ("CVS", "CVS Health"), ("AMGN", "Amgen"), ("VRTX", "Vertex Pharmaceuticals"),
    ("MRNA", "Moderna"), ("BIIB", "Biogen"), ("DXCM", "DexCom"),
    ("EW", "Edwards Lifesciences"), ("BDX", "Becton Dickinson"), ("BSX", "Boston Scientific"),
    ("ZBH", "Zimmer Biomet"), ("PLD", "Prologis"), ("AMT", "American Tower"),
    ("EQIX", "Equinix"), ("CCI", "Crown Castle"), ("SPG", "Simon Property Group"),
    ("O", "Realty Income"), ("SO", "Southern Company"), ("DUK", "Duke Energy"),
    ("D", "Dominion Energy"), ("SRE", "Sempra"), ("AEP", "American Electric Power"),
    ("EXC", "Exelon"), ("PANW", "Palo Alto Networks"), ("CRWD", "CrowdStrike"),
    ("FTNT", "Fortinet"), ("SNPS", "Synopsys"), ("CDNS", "Cadence Design"),
    ("ADI", "Analog Devices"), ("KLAC", "KLA Corp."), ("NXPI", "NXP Semiconductors"),
    ("MRVL", "Marvell Technology"), ("APH", "Amphenol"), ("MCHP", "Microchip Technology"),
    ("ON", "ON Semiconductor"), ("UBER", "Uber Technologies"), ("ABNB", "Airbnb"),
    ("SHOP", "Shopify"), ("SQ", "Block Inc."), ("COIN", "Coinbase"),
    ("PLTR", "Palantir Technologies"), ("SNOW", "Snowflake"), ("NET", "Cloudflare"),
    ("DDOG", "Datadog"), ("ZS", "Zscaler"), ("TEAM", "Atlassian"),
    ("WDAY", "Workday"), ("ZM", "Zoom Communications"), ("SPOT", "Spotify"),
    ("RBLX", "Roblox"), ("HOOD", "Robinhood Markets"), ("SOFI", "SoFi Technologies"),
    ("F", "Ford Motor"), ("GM", "General Motors"), ("RIVN", "Rivian"),
    ("DAL", "Delta Air Lines"), ("UAL", "United Airlines"), ("AAL", "American Airlines"),
    ("MAR", "Marriott International"), ("HLT", "Hilton Worldwide"), ("CCL", "Carnival Corp."),
    ("RCL", "Royal Caribbean"), ("CMG", "Chipotle"), ("ORLY", "O'Reilly Automotive"),
    ("AZO", "AutoZone"), ("ROST", "Ross Stores"), ("DG", "Dollar General"),
    ("DLTR", "Dollar Tree"), ("KR", "Kroger"), ("MO", "Altria Group"),
    ("CL", "Colgate-Palmolive"), ("KMB", "Kimberly-Clark"), ("MDLZ", "Mondelez International"),
    ("GIS", "General Mills"), ("K", "Kellanova"), ("HSY", "Hershey"),
    ("STZ", "Constellation Brands"), ("EA", "Electronic Arts"), ("TTWO", "Take-Two Interactive"),
    ("MMC", "Marsh & McLennan"), ("CB", "Chubb Ltd."), ("PGR", "Progressive Corp."),
    ("AIG", "American International Group"), ("MET", "MetLife"), ("PRU", "Prudential Financial"),
    ("AON", "Aon plc"), ("CME", "CME Group"), ("ICE", "Intercontinental Exchange"),
    ("MCO", "Moody's"), ("SHW", "Sherwin-Williams"), ("ITW", "Illinois Tool Works"),
    ("EMR", "Emerson Electric"), ("ETN", "Eaton Corp."), ("PH", "Parker-Hannifin"),
    ("ROK", "Rockwell Automation"), ("FDX", "FedEx"), ("NSC", "Norfolk Southern"),
    ("CSX", "CSX Corp."), ("WM", "Waste Management"), ("RSG", "Republic Services"),
    ("CTAS", "Cintas"), ("LMT", "Lockheed Martin"), ("NOC", "Northrop Grumman"),
    ("GD", "General Dynamics"), ("LHX", "L3Harris Technologies"), ("TDG", "TransDigm Group"),
]

OKX_CRYPTO = [
    ("BTC", "Bitcoin"), ("ETH", "Ethereum"), ("SOL", "Solana"),
    ("BNB", "BNB"), ("XRP", "XRP"), ("ADA", "Cardano"),
    ("DOGE", "Dogecoin"), ("AVAX", "Avalanche"), ("DOT", "Polkadot"),
    ("MATIC", "Polygon"), ("LINK", "Chainlink"), ("LTC", "Litecoin"),
    ("ATOM", "Cosmos"), ("UNI", "Uniswap"), ("XLM", "Stellar"),
    ("TRX", "TRON"), ("ALGO", "Algorand"), ("FTM", "Fantom"),
    ("NEAR", "NEAR Protocol"), ("FIL", "Filecoin"), ("ICP", "Internet Computer"),
    ("SAND", "The Sandbox"), ("MANA", "Decentraland"), ("AXS", "Axie Infinity"),
    ("AAVE", "Aave"), ("COMP", "Compound"), ("MKR", "Maker"),
    ("SNX", "Synthetix"), ("YFI", "yearn.finance"), ("SUSHI", "SushiSwap"),
    ("CRV", "Curve DAO"), ("1INCH", "1inch"), ("ENJ", "Enjin Coin"),
    ("CHZ", "Chiliz"), ("ZEC", "Zcash"), ("DASH", "Dash"),
    ("XMR", "Monero"), ("THETA", "Theta Network"), ("VET", "VeChain"),
    ("EOS", "EOS"), ("RNDR", "Render"), ("APT", "Aptos"),
    ("ARB", "Arbitrum"), ("OP", "Optimism"), ("INJ", "Injective"),
    ("SUI", "Sui"), ("TIA", "Celestia"), ("WLD", "Worldcoin"),
    ("PYTH", "Pyth Network"), ("JUP", "Jupiter"), ("SEI", "Sei"),
    ("TON", "Toncoin"), ("PEPE", "Pepe"), ("SHIB", "Shiba Inu"),
    ("WIF", "dogwifhat"), ("BONK", "Bonk"), ("FLOKI", "FLOKI"),
    ("ORDI", "ORDI"), ("STX", "Stacks"), ("IMX", "Immutable"),
    ("GRT", "The Graph"), ("LDO", "Lido DAO"), ("RPL", "Rocket Pool"),
    ("SSV", "SSV Network"), ("ENA", "Ethena"), ("PENDLE", "Pendle"),
    ("FET", "Fetch.ai"), ("AGIX", "SingularityNET"), ("OCEAN", "Ocean Protocol"),
    ("TAO", "Bittensor"), ("RENDER", "Render Token"), ("HBAR", "Hedera"),
    ("XTZ", "Tezos"), ("EGLD", "MultiversX"), ("FLOW", "Flow"),
    ("KAVA", "Kava"), ("MINA", "Mina"), ("ROSE", "Oasis Network"),
    ("ZIL", "Zilliqa"), ("IOTA", "IOTA"), ("NEO", "Neo"),
    ("QTUM", "Qtum"), ("WAVES", "Waves"), ("KSM", "Kusama"),
    ("RUNE", "THORChain"), ("CAKE", "PancakeSwap"), ("GMX", "GMX"),
    ("DYDX", "dYdX"), ("LPT", "Livepeer"), ("MASK", "Mask Network"),
    ("ENS", "Ethereum Name Service"), ("BLUR", "Blur"), ("MAGIC", "Magic"),
    ("GALA", "Gala"), ("APE", "ApeCoin"), ("GMT", "STEPN"),
    ("GST", "Green Satoshi Token"), ("LOOKS", "LooksRare"), ("CFX", "Conflux"),
    ("KAS", "Kaspa"), ("TWT", "Trust Wallet Token"), ("OKB", "OKB"),
    ("LEO", "UNUS SED LEO"), ("CRO", "Cronos"), ("BCH", "Bitcoin Cash"),
    ("BSV", "Bitcoin SV"), ("ETC", "Ethereum Classic"), ("AR", "Arweave"),
    ("STORJ", "Storj"), ("SC", "Siacoin"), ("W", "Wormhole"),
    ("STRK", "Starknet"), ("ZK", "zkSync"), ("MANTA", "Manta Network"),
    ("ALT", "Altlayer"), ("JTO", "Jito"), ("ONDO", "Ondo"),
    ("ETHFI", "ether.fi"), ("REZ", "Renzo"), ("EIGEN", "EigenLayer"),
    ("BOME", "BOOK OF MEME"), ("NOT", "Notcoin"), ("DOGS", "DOGS"),
    ("CATI", "Catizen"),
]

MARKET_UNIVERSE = {
    "alpaca": {
        "asset_class": "Equity",
        "quote": "USD",
        "items": [{"symbol": s, "name": n, "display": s} for s, n in ALPACA_STOCKS],
    },
    "okx": {
        "asset_class": "Crypto",
        "quote": "USDT",
        "items": [{"symbol": s, "name": n, "display": f"{s}/USDT"} for s, n in OKX_CRYPTO],
    },
}
